### ISSUE TITLE
Using vertical scrollbar sometimes doesn't show the last row completely

### ISSUE THREAD

**Issue by RalphLance** [BBj-Plugins/BBjGridExWidget#109]
When the grid is first displayed and not all rows fit cleanly in the grid's view area, then using the vertical scrollbar doesn't reach (aka show) the last row completely. Using the down arrow, PgDn or End keys does show the last row completely.

![image](https://user-images.githubusercontent.com/4834240/53574799-95604100-3b70-11e9-98f7-91f92d5f10af.png)

**Comment by hyyan** [comment]
@RalphLance you are correct it seems `16` pixels is added to the height when the HTMLView is drawn on the canvas.

@StephanWald I remember you writing this piece of code, could you please explain how you came up with this value ?! 

I have done some testing and the problem seems to come from the Widget size , the grid has always `100%` height 

![2019-02-28 19_03_47-](https://user-images.githubusercontent.com/4313420/53588917-54772500-3b8e-11e9-8b92-943b504f12c9.png)

**Comment by hyyan** [comment]
@RalphLance This is have been fixed in `dev` now .

The following is an example of a centered grid with margin which demonstrates the new correct calculation 

```java
use ::BBjGridExWidget/BBjGridExWidget.bbj::BBjGridExWidget
use com.basiscomponents.bc.SqlQueryBC
use java.sql.Types

? 'HIDE'

declare auto BBjTopLevelWindow wnd!
declare auto BBjListButton lb_db!
declare auto BBjListButton lb_tbl!
declare auto BBjToolButton btn_fit!
declare BBjGridExWidget grid!

x=30
y=30
w=740
h=540

BBjGridExWidget.setDebug(1)
wnd! = BBjAPI().openSysGui("X0").addWindow(10,10,800,600,"BBj Grid Ex Demo")
grid! = new BBjGridExWidget(wnd!,100,x,y,w,h)
wnd!        .setCallback(BBjAPI.ON_CLOSE,"byebye")
wnd!        .setCallback(BBjAPI.ON_RESIZE,"resize")

gosub fillGrid

process_events

fillGrid:

declare SqlQueryBC sbc!

sbc! = new SqlQueryBC(BBjAPI().getJDBCConnection("CDStore"))
rs! = sbc!.retrieve("SELECT  * FROM CDINVENTORY")
grid!.setData(rs!)
return

byebye:
bye

resize:
ev! = BBjAPI().getLastEvent()
w!=ev!.getWidth() - 60
h!=ev!.getHeight() - 60
grid!.setSize(w! ,h! )
return

```
