### ISSUE TITLE
calling clearRowsData() before setData() in a brand new grid will result in an empty grid display

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#115]
run demo.bbj from the branch clearRowsBeforeSetData. It goes into "doQuery" right after creating the grid which loads the data if clearRowsData() is not present in the beginning of the routine. If the grid data is cleared (as it can happen in generic code) a subsequent call to setData will not load the data. Any further call to doQuery works as expected.

**Comment by hyyan** [comment]
@StephanWald I think this is the correct behavior. you are trying to call `clearRowsData()` before the grid is ready. this method is meant for clearing already created grid by settings an empty array.

The execution order in this demo will always be like : 
1. setData()
2. clearRowsData()

Because BBj will not attempt to execute any JS function before the `#IsReady!` flag is true. before the grid is ready [all calls will be queued in the backlog ](https://github.com/BBj-Plugins/BBjGridExWidget/blob/master/BBjGridExWidget.bbj#L1647)then the backlog will be flushed.

**Comment by hyyan** [comment]
@StephanWald please review again

**Comment by hyyan** [comment]
The behavior will not be changed
