### ISSUE TITLE
edit mode active by default / unable to disable editmode? 

### ISSUE THREAD

**Issue by RVDHofDAGOCAR** [BBj-Plugins/BBjGridExWidget#187]
Hi, pls consider the snippets.

setting edit mode to false:
![image](https://user-images.githubusercontent.com/55919456/69421694-f42ea180-0d21-11ea-9eee-3e8e79dcb1ad.png)

but a doubleclick in a cell (I would like to select the row only) will affect in editing by the way:
![image](https://user-images.githubusercontent.com/55919456/69421732-12949d00-0d22-11ea-85ca-99f79758284e.png)

 seems that I am not handling the grid in the correct way.
 But can't test it as well with the given "selection demo". 
This crashs when I perform a double click.

Using the latest released version of the plugin.

What goes wrong? Thx

**Comment by hyyan** [comment]
@RVDHofDAGOCAR Edit mode is disabled by default for all columns. In case you are building the grid columns from the ResultSet using the `setData` method then the grid will check if the column attribute `Editable` (case insensitive) is present and enable editing on the column. 
` grid!.getOptions().setEditable(Boolean)` updates only the [DefaultColumnDefinfition ](https://bbj-plugins.github.io/BBjGridExWidget/javadoc/BBjGridExWidget/BBjGridExWidgetOptions.html#DefaultColumnDefinition!)

You can remove the `Editable` attribute from your resultset. or you can use the column api like this 
`grid!.getColumn("Title").setEditable(0)`

```java
? 'HIDE'

use ::BBjGridExWidget/BBjGridExWidget.bbj::BBjGridExWidget
use com.basiscomponents.db.ResultSet
use com.basiscomponents.bc.SqlQueryBC

declare auto BBjTopLevelWindow wnd!
declare BBjGridExWidget grid!

wnd! = BBjAPI().openSysGui("X0").addWindow(10,10,800,600,"Simple CD-Store Demo")
wnd!.setCallback(BBjAPI.ON_CLOSE,"byebye")

gosub main
process_events

main:
  declare SqlQueryBC sbc!
  declare ResultSet rs!
  
  sbc! = new SqlQueryBC(BBjAPI().getJDBCConnection("CDStore"))
  rs! = sbc!.retrieve("SELECT  * FROM CDINVENTORY")
  rem // make the the TITLE column editable
  rs!.setAttribute(1, "EDITABLE", "1")

  grid! = new BBjGridExWidget(wnd!,100,0,0,800,600)

  rem //make all columns editable by default 
  rem grid!.getOptions().setEditable(1)

  grid!.setData(rs!) 
  
  rem // disable column editing on TITLE
  grid!.getColumn("TITLE").setEditable(0)
return

byebye:
bye
```

**Comment by hyyan** [comment]
@RVDHofDAGOCAR did my answer solve your problem, may I close the issue?

**Comment by RVDHofDAGOCAR** [comment]
Hyyan,
Yes – has been solved - thank you for your quick response.
(Maybe be you can just create a manual implementation of the setter and getter of the setEnabled(..) property.
And if it is explicite set to 0, ignore all EDITABLE flags of the field attributes !? Would be more sophisticated
In my opion)

Thx
Br
Ralf


Von: Hyyan Abo Fakher <notifications@github.com>
Gesendet: Montag, 25. November 2019 09:46
An: BBj-Plugins/BBjGridExWidget <BBjGridExWidget@noreply.github.com>
Cc: Ralf Vandenheuvel <ralf.vandenheuvel@dagocar.com>; Mention <mention@noreply.github.com>
Betreff: Re: [BBj-Plugins/BBjGridExWidget] edit mode active by default / unable to disable editmode? (#187)


@RVDHofDAGOCAR<https://github.com/RVDHofDAGOCAR> did my answer solve your problem, may I close the issue?

**Comment by hyyan** [comment]
@RVDHofDAGOCAR the methods defined in the options interface like `setEditable`, `setEnableFilter`,... were meant to set up the default configuration for the new columns. these configurations can be overridden on the column level, once you create the column manually or from ResultSet by using the `setData` method. this architecture is for modularity, you start with common settings and you override on the module level, structuring this the other way around will be confusing

**Comment by RVDHofDAGOCAR** [comment]
Okay, thank you – maybe you can extend the online description of that setoptions…setEditable(..) method to underline the intention more in detail and that it is not possible to swap the editable status of the whole grid anytime.

[cid:image001.png@01D5A382.19728830]

Von: Hyyan Abo Fakher <notifications@github.com>
Gesendet: Montag, 25. November 2019 11:11
An: BBj-Plugins/BBjGridExWidget <BBjGridExWidget@noreply.github.com>
Cc: Ralf Vandenheuvel <ralf.vandenheuvel@dagocar.com>; Mention <mention@noreply.github.com>
Betreff: Re: [BBj-Plugins/BBjGridExWidget] edit mode active by default / unable to disable editmode? (#187)


@RVDHofDAGOCAR<https://github.com/RVDHofDAGOCAR> the methods defined in the options interface like setEditable, setEnableFilter,... were meant to set up the default configuration for the new columns. these configurations can be overridden on the column level, once you create the column manually or from ResultSet by using the setData method. this architecture is for modularity, you start with common settings and you override on the module level, structuring this the other way around will be confusing

**Comment by hyyan** [comment]
@RVDHofDAGOCAR The [method ](https://bbj-plugins.github.io/BBjGridExWidget/javadoc/BBjGridExWidget/BBjGridExWidgetOptions.html#setEditable-BBjNumber-)is tagged with two tags `#Configuration` & `ColumnsRerender`.
Tags meaning are described in the following [table ](https://bbj-plugins.github.io/BBjGridExWidget/javadoc/BBjGridExWidget/BBjGridExWidgetOptions.html)

| Tag             | Description                                                                                                                                                                                                                                                                                                                                                               |
|-----------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **#Configuration**   | Properties and methods which are tagged with this tag are used to configure the grid before it is rendered on the client·  Changing these properties or calling these methods won't affect the grid which is displayed on the client·  In order to reflect your changes on the client, you need to rerender the whole grid  or rerender the column definition once again· |
| **#ColumnsRerender** | Changing this property or calling this method after the first render require columns rerender using  updateColumns() method                                                                                                                                                                                                                                               |
