### ISSUE TITLE
Error 26 in Stmt 1082 of BBjGridExWidgetColumns.bbj

### ISSUE THREAD

**Issue by RVDHofDAGOCAR** [BBj-Plugins/BBjGridExWidget#194]
#### What product versions and settings are you using when this issue occurs?
* BBj: 18.21
* BBjGridExWidget: 0.100.3
* Platform (GUI or BUI): GUI
* Browser: NONE /GUI / the embedded one used by the BBjGridExWidget :-)

#### Steps to Reproduce
1. 
1. 
1. 

#### What I Expected

No error 26

#### What Happened Instead
see screenshot
![image](https://user-images.githubusercontent.com/55919456/72415776-82009900-3775-11ea-9e2d-516ad38c2eef.png)

best regards
Ralf

**Comment by hyyan** [comment]
@RVDHofDAGOCAR are you by any chance using this method [ResultSet.fromJson ](https://basishub.github.io/components/javadoc/com/basiscomponents/db/ResultSet.html#fromJson-java.lang.String-)to set the ResultSet ?

This issue has been already fixed in dev [here ](https://github.com/BBj-Plugins/BBjGridExWidget/commit/2d14d3fda974e1d20dc31c117e2ca80422f8a1cd). You can get the new version `0.100.4` manually from [here](https://github.com/BBj-Plugins/BBjGridExWidget/archive/0.100.4.zip) or just wait for the Plugins manager to detect the new version.
