### ISSUE TITLE
RENDERER_MASK field attribute and java.sql.Types.NUMERIC nnnnnn -> 00:00:00

### ISSUE THREAD

**Issue by RVDHofDAGOCAR** [BBj-Plugins/BBjGridExWidget#199]
#### What product versions and settings are you using when this issue occurs?
* BBj: 18.21
* BBjGridExWidget: 0.100.4
* Platform (GUI or BUI): GUI
* Browser:

#### Steps to Reproduce
1. in our database a numeric column containing a time represent value of hhmmss
1. would like RENDER a NUMERIC Value of 153417 to the output of 15:34:17
1. is there a way to perform it via the RENDERER_MASK or any other inbuilt solution

#### What I Expected
15:34:17

#### What Happened Instead
153417

**Comment by hyyan** [comment]
@RVDHofDAGOCAR you can use **MASK** as a field attribute instead of the deprecated **RENDERER_MASK** or you can set this programmatically 

@see 

1. [DatatypesDemo ](https://github.com/BBj-Plugins/BBjGridExWidget/blob/dev/demo/DatatypesDemo.bbj#L127)
2. [CustomGridDemo](https://github.com/BBj-Plugins/BBjGridExWidget/blob/dev/demo/CustomGridDemo.bbj)
