### ISSUE TITLE
improve row selection event when grid is tree grid

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#5]
From customer:
J'ai activé l'évènement "ON_GRID_SELECT_ROW" 
myGrid!.setSelectionMode(myGrid!.GRID_SELECT_ROW())

Le problème est que je n'ai le retour que sur les lignes de terminaison d'arbres et pas sur les nœuds intermédiaires, ce qui ne nous convient pas. 
De plus, le retour de cet évènement "getSelectedRowCount()" est le numéro d'ordre de la terminaison. Ce n'est pas facile de retrouver les données associées

**Comment by hyyan** [comment]
@StephanWald 

The selection event has been improved a lot with these commits, but with a lot of Break changes too which are necessary, I summarize the changes here 

**1 )  ON_GRID_SELECT_ROW** reflects changes in selection and deselection at the same time now 

**2 )** Rows are represented with **BBjGridExWidgetRow** class now. the class contains the following public fields which describe the row:

- **BBjString Id!**  _The Row ID which can be auto-generated by ag-grid or set by the developer_
- **BBjNumber ChildIndex!**  _The index of the row, if the row has a parent then it is the child index_ 
-  **BBjString ParentKey!** _The parent key of the row if it has a parent, otherwise it is always `-1`_
- **BBjNumber IsSelected!** _A flag which describes whether the row is selected or not [0,1]_
- **JsonObject Data!** _The row data as JsonObject (It contains the meta data too)_

**3  ) getSelectedRows** returns a Java **hashmap** instead of **BBjVector** of selected rows. the map keeps tracking selected/deselected rows where each row is an instance of **BBjGridExWidgetRow** , this map is needed because the selection event reports the last selected/deselected rows only and it does not report all selected /deselected rows previously. 
**Ex  :** A dummy scenario which describes the need for this method 
1.  User selects row `x` 
2.  An event is fired reports row 5 selection 
3. User selects new row `y`
4.  An event is fired reports row `y` selection ONLY
The **getSelectedRows** method will return a hashmap with two rows [x,y] according to the previous scenario even though according to the last event only `y` row is selected

**4  ) getSelectedRow** returns an instance of **BBjGridExWidgetRow** instead of a **BBjNumber**  

**5  ) BBjGridExWidgetSelectRowEvent** class manages now all selected/deselected rows.
The class contains the following public methods to speed things up.

- **getRowCount()** : Get the number of affected rows by the last selection event
- **getSelectedRowCount()** : Get the number of selected rows by the last selection event. 
- **getDeselectedRowCount()** : Get the number of deselected rows by the last selection event
- **getSelectedIds()** : Returns a BBjVector which contains the IDs of selected rows 
- **getDeselectedIds()** : Returns a BBjVector which contains the IDs of deselected rows 
- **getRows()** : Get all affted rows by the last selection event as objects
- **getSelectedRows()** : Get all selected rows by the last selection event as objects. (the GRID  methods `getSelectedRows()` or `getSelectedRow()` can be used instead )
- **getDeselectedRows()** : Get all deselected rows by the last selection event as objects

**Ex :** from `TreeDemo.bbj` demo

```java
onRowSelect:
    ev! = BBjAPI().getLastEvent()
    ev! = ev!.getObject()
    print 'SHOW', ev!.getRowCount(), " ROW(s) AFFECTED By Event:" , ev!.getRows()
    print 'SHOW', ev!.getSelectedRowCount()," ROW(S) SELECTED By Event: ",ev!.getSelectedIds()
    print 'SHOW', ev!.getDeselectedRowCount()," ROW(S) DESELECTED By Event: ",ev!.getDeselectedIds()
    print 'SHOW', grid!.getSelectedRows().size()," ROW(S) SELECTED SO FAR : ", grid!.getSelectedRows()
    print 'SHOW', "------------------------------------------------------------------------"
return 
```

![capture](https://user-images.githubusercontent.com/4313420/35924223-bd7b3d3a-0c22-11e8-8b3c-38bdd203c47a.PNG)

**Ex :** from `ColumnSetupDemo` demo

```java
onRowSelect: 
    selectedRow! = grid!.getSelectedRow()
    a = msgbox(selectedRow!.getId(), 0, selectedRow!.getData().get("TITLE").getAsString())
return    
```

**6  ) BBjGridExWidgetDoubleClickRowEvent** class contains the "double clicked" row as BBjGridExWidgetRow instance now instead of a number

**Ex :** from `ColumnSetupDemo` demo

```java
onRowDoubleclick:
    ev! = BBjAPI().getLastEvent()
    ev! = ev!.getObject()
    row! = ev!.getRow()
   msgbox(row!.getId() + " - " + row!.getData().get("TITLE").getAsString(),0,"DOUBLE CLICK")
return  
```

**7  ) setData( ResultSet rs! ,BBjString RowNodeId$)**  a new overload method which allows setting the field used as a row ID.

**Ex  :** from `ColumnSetupDemo` demo

```java
fillGrid:

    declare SqlQueryBC sbc!
    sbc! = new SqlQueryBC(BBjAPI().getJDBCConnection("CDStore"))
    rs! = sbc!.retrieve("SELECT  * FROM CDINVENTORY")
    
    /** CDNUMBER field is used as an ID for rows */
    grid!.setData(rs!,"CDNUMBER")
return
```

![capture](https://user-images.githubusercontent.com/4313420/35925160-4fd16180-0c25-11e8-84eb-fbfa55de83e4.PNG)

**8  ) setData( DataTree rs! ,BBjString RowNodeId$ , BBjString ParentNodeId$)** a new overload method which allows setting the parent ID (key) when `DataTree` is used as a source 

**Ex  :**  from `TreeDemoe` demo

```java
fillGrid:

    qbc! = new SqlQueryBC(BBjAPI().getJDBCConnection("ChileCompany"))

    sql$="SELECT TOP 2
:   trim(LAST_NAME)+', '+trim(FIRST_NAME)+' ('+trim(CUST_NUM)+')'  AS '__node__name',
:   CUST_NUM        ,
:   CITY            ,
:   STATE           ,
:   COUNTRY         ,
:   FROM CUSTOMER "


    dt! = new DataTree()
    
    c1! = dt!.getRoot().addChild("Domestic Customers")
    c11! = c1!.addChild("New Mexico")
    
    r! = qbc!.retrieve(sql$+"WHERE COUNTRY='US' AND STATE != 'NM'")
    
    c11!.setResultSet(r!)
    c11!.setFieldValue("STATE","(other)")
    
    x11 = r!.sum("SALES_YTD")
    y11 = r!.sum("SALES_LY")
    
    c11!.setFieldValue("SALES_YTD", x11)
    c11!.setFieldValue("SALES_LY", y11)
    
    /** Set Unique Parent ID */
    c11!.setFieldValue("PARENT_ID", "CUSTOMERS_MEXICO")
    c1!.setFieldValue("PARENT_ID", "CUSTOMERS")
    
    grid!.addColumn("COMPANY","Company Name")
    grid!.addColumn("CITY","Town")
    grid!.addColumn("STATE","State")
    grid!.addColumn("COUNTRY","Country")
    grid!.addColumn("SALES_YTD","Sales YTD",8)
    grid!.addColumn("SALES_LY","Sales Prev.Y.",8)
    
    /** Use `PARENT_ID` as parent key and `CUST_NUM` as row id */
    grid!.setData(dt!,"CUST_NUM","PARENT_ID")    
return
```
