### ISSUE TITLE
how to define subtotals?

### ISSUE THREAD

**Issue by StephanWald** [BBj-Plugins/BBjGridExWidget#99]
We already had a working implementation of subtotals. Is this available in the released version? If so we need a sample for that.
how did we implement this? Was it "row pinning" ?
https://www.ag-grid.com/javascript-grid-row-pinning/

**Comment by hyyan** [comment]
@StephanWald I do not really understand what do you mean by `subtotals` . Are you talking about Aggregation ?! Maybe check the `Enterprise/AggregationDemo.bbj` demo.

Row pinning was never implemented, we had a discussion about it before, and we decided to ignore this feature, the problem, as I can recall, was that pinned rows are not part of the row model(ResultSet). so the feature is useless in the BBjGridExWidget context because you can not select some rows from the model and pin them to the top or the bottom.
pinned rows (top/bottom) are Javascript objects which can contain strings and they have no access to the grid options or model.

I can not see any benefit from exposing this feature to BBj developers. 
Do you have a use case for this feature in BBj?

**Comment by hyyan** [comment]
@StephanWald  closing as Row pinning is not a useful feature currently and it has no real application for BBj.
Please re-open if you think otherwise
